---
name: 'Pull Request Dependency Check'
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.0.2'
    - name: Get swift version
      run: swift --version
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run snapshot action
      uses: vapor-community/swift-dependency-submission@v0.1

